"use client"
import {useState,type ReactNode} from 'react'
import Link from 'next/link'
import {blankBatch,calculate,type Batch,type Extra} from './model'
import {saveCosting,type SavedBatch} from './actions'
const fmt=(n:number)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:3}).format(n)
function Box({title,children}:{title:string;children:ReactNode}){return <section className="bc-box"><h2>{title}</h2>{children}</section>}
function ExtraRows({rows,onChange}:{rows:Extra[];onChange:(rows:Extra[])=>void}){return <div>{rows.map((r,i)=><div className="bc-extra" key={i}><input aria-label="اسم الإضافة" placeholder="طحينة / عيش / تغليف" value={r.name} onChange={e=>onChange(rows.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input aria-label="الكمية" type="number" min={0} step="0.0001" placeholder="الكمية" value={r.quantity||''} onChange={e=>onChange(rows.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/><input aria-label="سعر الوحدة" type="number" min={0} step="0.0001" placeholder="سعر الوحدة" value={r.unitPrice||''} onChange={e=>onChange(rows.map((x,j)=>j===i?{...x,unitPrice:Number(e.target.value)}:x))}/><button onClick={()=>onChange(rows.filter((_,j)=>j!==i))}>حذف</button></div>)}<button className="bc-soft" onClick={()=>onChange([...rows,{name:'',quantity:0,unitPrice:0}])}>+ إضافة مكوّن أو تغليف</button><p className="bc-help">الكمية وسعر الوحدة بنفس الوحدة: 0.02 كيلو × سعر الكيلو، أو 1 رغيف × سعر الرغيف.</p></div>}
export function CostingPanel({initial}:{initial:SavedBatch[]}){
 const [b,setB]=useState<Batch>(blankBatch),[saved,setSaved]=useState(initial),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const r=calculate(b)
 const update=<K extends keyof Batch>(key:K,value:Batch[K])=>setB({...b,[key]:value})
 const field=(key:keyof Batch,label:string)=><label className="bc-field"><span>{label}</span><input type="number" min="0" max="100000000" step="0.0001" value={typeof b[key]==='number'?(b[key] as number)||'':''} onChange={e=>update(key,Number(e.target.value) as Batch[typeof key])}/></label>
 async function save(){if(busy)return;const id=b.id||crypto.randomUUID(),next={...b,id};setB(next);setBusy(true);try{const result=await saveCosting(next);setMessage(result.message);if(result.saved)setSaved(result.saved)}catch{setMessage('تعذر الاتصال. اضغط حفظ مجددًا؛ لن ننشئ نسخة ثانية من نفس الدفعة.')}finally{setBusy(false)}}
 function download(){const out={exportedAt:new Date().toISOString(),current:{input:b,result:r},saved};const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='el7bbob-batch-costing.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main dir="rtl" className="bc-root"><style>{`.bc-root{background:#f6f3ed;color:#202c25;min-height:100vh;padding:24px}.bc-wrap{max-width:1180px;margin:auto}.bc-head{padding:26px;background:#182720;color:white;border-radius:22px;margin-bottom:20px}.bc-head h1{font-size:27px;font-weight:900}.bc-head a{color:#f5b545}.bc-box{background:white;border:1px solid #e2ded4;border-radius:18px;padding:22px;margin:18px 0}.bc-box h2{font-size:21px;font-weight:900;margin-bottom:15px}.bc-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.bc-field{display:flex;flex-direction:column;gap:6px;font-weight:700;font-size:14px}.bc-root input,.bc-root textarea,.bc-root select{border:1px solid #dcded5;background:#fafbf7;padding:11px;border-radius:10px;width:100%;color:#202c25}.bc-help{font-size:13px;color:#647269;line-height:1.9;margin:12px 0}.bc-button,.bc-soft{padding:11px 17px;border-radius:10px;background:#f5b545;font-weight:800;color:#182720}.bc-soft{background:#eee9dc}.bc-extra{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:8px;margin-bottom:10px}.bc-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.bc-stat{padding:18px;background:#182720;color:white;border-radius:14px}.bc-stat strong{display:block;color:#f5b545;font-size:25px}.bc-actions{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.bc-errors{background:#fff1d6;padding:15px;border-radius:12px;line-height:2}.bc-table{width:100%;border-collapse:collapse;white-space:nowrap}.bc-table th,.bc-table td{padding:12px;border-bottom:1px solid #eee;text-align:right}.bc-scroll{overflow:auto}.bc-label{background:#f4e8cb;display:inline-block;padding:5px 9px;border-radius:8px;margin:8px 0}.bc-root button:disabled{opacity:.45}.bc-wide{grid-column:1/-1}@media(max-width:720px){.bc-root{padding:12px}.bc-grid,.bc-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.bc-extra{grid-template-columns:1fr 1fr}.bc-box{padding:16px}.bc-head h1{font-size:22px}}`}</style><div className="bc-wrap">
 <header className="bc-head"><Link href="/staff/owner">← مساحة المالك</Link><h1>من الشيكارة لحد الساندوتش</h1><p>تكلفة الدفعة، فاقد التحضير، الزيت والغاز، والحصة النهائية</p></header>
 <p className="bc-help">حاسبة دفعات محفوظة خاصة بالمالك، وليست ترحيلًا للمخزون أو دفتر المبيعات. تغيير الأرقام هنا لا يخصم خامات ولا يكرر مبيعات تقفيل اليوم. الأسعار والكميات تدخلها أنت؛ لا توجد قيم تكلفة تجريبية.</p>
 <Box title="1. الدفعة وشراء الخام"><div className="bc-grid"><label className="bc-field">اسم الدفعة / الخامة<input value={b.name} maxLength={120} placeholder="فول متدمس / بطاطس / باذنجان / طعمية" onChange={e=>update('name',e.target.value)}/></label><label className="bc-field">تاريخ الدفعة<input type="date" value={b.date} onChange={e=>update('date',e.target.value)}/></label>{field('purchaseKg','وزن الشيكارة أو الشوال بالكيلو')}{field('purchaseCost','ثمن العبوة بالجنيه')}{field('freight','النقل والتكاليف المباشرة للعبوة')}{field('rawKg','الخام المسحوب لهذه الدفعة بالكيلو')}</div><p className="bc-help">تكلفة الكيلو الخام: {fmt(r.rawUnit)} ج.م • تكلفة الخام المستخدم: {fmt(r.rawCost)} ج.م. لو عندك عدة عبوات بأسعار مختلفة، أدخل مجموع أوزانها وتكلفتها لتقدير المتوسط.</p></Box>
 <Box title="2. وزن التنظيف والناتج النهائي"><div className="bc-grid">{field('cleanKg','وزن بعد التنظيف / التقشير قبل الطبخ')}{field('cookedKg','وزن الناتج الصالح بعد الطبخ / القلي والتصفية')}{field('wasteKg','هالك الناتج الجاهز بالكيلو')}{field('staffKg','أكل العاملين / الضيافة من الناتج بالكيلو')}</div><p className="bc-help">فاقد تنظيف مسجل: {fmt(Math.max(0,b.rawKg-b.cleanKg))} كيلو • معامل الناتج النهائي: {b.rawKg>0?fmt(b.cookedKg/b.rawKg):'—'}. الفول قد يزيد بالمياه، والبطاطس قد يقل وزنها. لا تسجل قشر البطاطس مرة ثانية في هالك الناتج؛ فاقد التنظيف داخل تكلفة الناتج بالفعل. الهالك غير الطبيعي ظاهر منفصلًا.</p></Box>
 <Box title="3. المكونات الداخلة في الدفعة"><ExtraRows rows={b.extras} onChange={v=>update('extras',v)}/><p className="bc-help">دي كميات الدفعة كلها، مثل الملح والبصل والتوابل. إضافات الساندوتش تُسجل تحت لكل وحدة، ولا تكرر نفس المكوّن في المكانين.</p></Box>
 <Box title="4. دورة الزيت المشتركة"><div className="bc-grid">{field('oilStart','لترات الزيت في بداية الدورة')}{field('oilAdded','لترات الزيت المضافة خلال الدورة')}{field('oilLeft','لترات متبقية صالحة للاستخدام')}{field('oilPrice','متوسط تكلفة لتر الزيت')}{field('oilBatchWeight','وزن ما قُلي من هذه الدفعة بالكيلو')}{field('oilFactor','معامل توزيع لهذه الدفعة')}{field('oilOtherWeight','مجموع أوزان باقي الدفعات × معامل كل واحدة')}</div><span className="bc-label">توزيع تكلفة الزيت تقديري، وليس قياس امتصاص فعلي</span><p className="bc-help">المستهلك/المستبعد = البداية + الإضافات − المتبقي الصالح: {fmt(r.oilUsed)} لتر. تكلفة الدورة: {fmt(r.cycleOilCost)} ج.م • نصيب الدفعة: {fmt(r.oilCost)} ج.م. وزن الدفعة × معاملها يُقسم على مجموع الأوزان المرجحة. المعامل 1 يعني توزيعًا متساويًا بالوزن، لا يعني أن كل المنتجات تمتص الزيت بالتساوي. لا تضف تكلفة الزيت هنا ثم تكررها ضمن مكونات الدفعة. التخلص من الزيت تحكمه سلامته وجودته، وليس الحساب المالي.</p></Box>
 <Box title="5. الغاز"><div className="bc-grid">{field('gasCylinderKg','صافي وزن الغاز بالأسطوانة أو مجموع الأسطوانات')}{field('gasCylinderCost','تكلفة الغاز لهذه الكمية')}{field('gasUsedKg','كيلوجرامات الغاز المستهلكة في هذه الدفعة')}<label className="bc-field">مصدر استهلاك الغاز<select value={b.gasEstimated?'estimated':'measured'} onChange={e=>update('gasEstimated',e.target.value==='estimated')}><option value="estimated">توزيع تقديري</option><option value="measured">مقاس فعليًا</option></select></label></div><p className="bc-help">تكلفة غاز الدفعة: {fmt(r.gasCost)} ج.م — {b.gasEstimated?'تقديرية':'وفق قياسك'}. الوزن هنا صافي الغاز لا وزن الأسطوانة المعدني. لو بتوزع حسب وقت الشعلة، حوّل نصيب الدفعة إلى كيلو تقديري وسجله؛ لا يُحسب العمر التشغيلي تلقائيًا.</p></Box>
 <Box title="6. نصيب التشغيل: إيجار وعمال ومرافق"><div className="bc-grid">{field('rent','إيجار شهري')}{field('wages','أجور شهرية')}{field('utilities','مرافق شهرية — بدون الغاز المحسوب فوق')}{field('otherMonthly','مصروفات تشغيل شهرية أخرى — بدون الزيت والخامات')}{field('operatingDays','عدد أيام التشغيل بالشهر')}{field('batchOverheadPercent','نصيب هذه الدفعة من تشغيل يومها %')}</div><span className="bc-label">نصيب التشغيل تقديري</span><p className="bc-help">تشغيل اليوم: {fmt(r.daily)} ج.م • نصيب هذه الدفعة: {fmt(r.overhead)} ج.م. وزع 100% فقط بين جميع دفعات اليوم، ولا تسجل 100% لكل دفعة. لو الدفعة تخدم عدة أيام، قسمها على أيامها أو أدخل نصيب تشغيلها المجمع ضمن المصروفات المناسبة. هذه الحاسبة لا تتحقق تلقائيًا من مجموع توزيع الدفعات المختلفة.</p></Box>
 <Box title="7. الساندوتشات والعلب وحصة كل واحد">{b.products.map((p,i)=><section className="bc-box" key={i}><div className="bc-grid"><label className="bc-field">اسم المنتج / الحجم<input value={p.name} maxLength={120} onChange={e=>update('products',b.products.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></label>{(['grams','price','sold'] as const).map(key=><label className="bc-field" key={key}>{key==='grams'?'حصة الناتج الجاهز بالجرام':key==='price'?'سعر بيع الوحدة':'عدد الوحدات المباعة'}<input type="number" min={0} step={key==='sold'?1:0.001} value={p[key]||''} onChange={e=>update('products',b.products.map((x,j)=>j===i?{...x,[key]:Number(e.target.value)}:x))}/></label>)}</div><p className="bc-help">إضافات وحدة واحدة: عيش، طحينة، خضار، علبة، غطاء، كيس…</p><ExtraRows rows={p.extras} onChange={extras=>update('products',b.products.map((x,j)=>j===i?{...x,extras}:x))}/><button className="bc-soft" onClick={()=>update('products',b.products.filter((_,j)=>j!==i))}>حذف المنتج من الحساب</button></section>)}<button className="bc-button" onClick={()=>update('products',[...b.products,{name:'',grams:0,price:0,sold:0,extras:[]}])}>+ منتج أو حجم آخر</button><p className="bc-help">الحصة تُوزن فعلًا أول مرة؛ لا يمكن استنتاج جرامات الساندوتش والعلبة معًا من إجمالي المبيعات وحده. الأعداد تدخل في نهاية اليوم، مش أثناء كل طلب.</p></Box>
 <Box title="النتيجة — حسب بياناتك">{r.errors.length>0?<div className="bc-errors">{r.errors.map((e,i)=><p key={i}>{e}</p>)}<p>الأرقام التالية مسودة، لا تعتمد عليها قبل تصحيح المدخلات.</p></div>:<span className="bc-label">المدخلات متسقة حسابيًا؛ صحة القياسات مسؤولية التشغيل</span>}<div className="bc-stats">{[{t:'تكلفة إنتاج الدفعة',v:r.totalDirect},{t:'تكلفة كيلو الناتج',v:r.costKg},{t:'المبيعات المسجلة للدفعة',v:r.revenue},{t:'الناتج المتبقي — كيلو',v:r.remaining}].map(x=><div className="bc-stat" key={x.t}>{x.t}<strong>{fmt(x.v)}</strong></div>)}</div><div className="bc-scroll"><table className="bc-table"><thead><tr><th>المنتج</th><th>جرام</th><th>تكلفة مباشرة</th><th>بالتشغيل الموزع</th><th>سعر البيع</th><th>هامش الوحدة التقديري</th><th>عدد مباع</th><th>نظريًا لو كل الدفعة لهذا المنتج</th></tr></thead><tbody>{r.products.map((p,i)=><tr key={i}><td>{p.name}</td><td>{fmt(p.grams)}</td><td>{fmt(p.direct)}</td><td>{fmt(p.full)}</td><td>{fmt(p.price)}</td><td>{fmt(p.margin)}</td><td>{p.sold}</td><td>{p.theoretical}</td></tr>)}</tbody></table></div><p className="bc-help">مستخدم في المبيعات: {fmt(r.soldKg)} كيلو • تكلفة الهالك: {fmt(r.wasteCost)} • أكل العاملين: {fmt(r.staffCost)} • قيمة الناتج المتبقي مباشرة: {fmt(r.remainingValue)} ج.م.</p><p><b>هامش المبيعات بعد نصيب التشغيل المباع والهالك والضيافة: {fmt(r.estimatedMargin)} ج.م — تقديري، وليس صافي ربح المحل.</b></p><p className="bc-help">لا نجمع السعات النظرية للأصناف؛ كلها تستخدم نفس الدفعة. المتبقي مخزون وليس مبيعًا. التقرير لا يحسب الضرائب والتمويل والالتزامات ولا يوزع تلقائيًا المصروفات بين أيام ودفعات متعددة.</p></Box>
 <Box title="الحفظ والدفعات السابقة"><label className="bc-field">ملاحظات وقياساتك<textarea value={b.note} maxLength={2000} onChange={e=>update('note',e.target.value)}/></label><div className="bc-actions"><button disabled={busy||r.errors.length>0} className="bc-button" onClick={()=>void save()}>{busy?'جارٍ الحفظ…':b.id?'حفظ تعديل الدفعة':'حفظ حساب الدفعة'}</button><button className="bc-soft" onClick={()=>{if(window.confirm('فتح دفعة جديدة؟ أي تعديل غير محفوظ سيُفقد.')){setB(blankBatch());setMessage('')}}}>دفعة جديدة</button><button className="bc-soft" onClick={download}>تحميل كل حساباتي JSON</button><button className="bc-soft" onClick={()=>window.print()}>طباعة / PDF</button></div>{message&&<p role="status" className="bc-errors">{message}</p>}<div className="bc-actions">{saved.map(s=><button className="bc-soft" key={s.id} onClick={()=>{if(!b.name||window.confirm('فتح الدفعة المحفوظة؟ التعديل غير المحفوظ سيُفقد.')){setB(structuredClone(s.data));setMessage('')}}}>{s.data.name} — {s.data.date}</button>)}</div></Box>
 </div></main>
}
