export const SITE_COPY_FIELDS=[
	{key:"home.orderNow",group:"الصفحة الرئيسية",label:"زر الطلب",sources:["اطلب دلوقتي","اطلب الآن"],defaultText:"اطلب الآن"},
	{key:"home.heroTitle",group:"الصفحة الرئيسية",label:"العنوان الرئيسي",sources:["طعم بلدي، بلمسة عالمية"],defaultText:"طعم بلدي، بلمسة عالمية"},
	{key:"home.menu",group:"الصفحة الرئيسية",label:"عنوان قائمة الطعام",sources:["المينيو","قائمة الطعام"],defaultText:"قائمة الطعام"},
	{key:"home.sandwiches",group:"أقسام القائمة",label:"قسم الساندويتشات",sources:["الساندوتشات","الساندويتشات"],defaultText:"الساندويتشات"},
	{key:"home.mixes",group:"أقسام القائمة",label:"قسم الميكسات",sources:["الميكسات","روقان الحبوب"],defaultText:"روقان الحبوب"},
	{key:"home.platters",group:"أقسام القائمة",label:"قسم الأطباق",sources:["الأطباق والوجبات","علب وطبلية الفطار"],defaultText:"علب وطبلية الفطار"},
	{key:"home.boxes",group:"أقسام القائمة",label:"قسم البوكسات",sources:["بوكسات الفطار"],defaultText:"بوكسات الفطار"},
	{key:"home.packs",group:"أقسام القائمة",label:"قسم العلب والباكيتات",sources:["علب وباكيتات"],defaultText:"علب وباكيتات"},
	{key:"home.breakfastTrays",group:"أقسام القائمة",label:"قسم طبلية الفطار",sources:["طبلية فطار"],defaultText:"طبلية فطار"},
	{key:"home.breakfastBoxes",group:"أقسام القائمة",label:"قسم بوكس الفطار",sources:["بوكس فطار"],defaultText:"بوكس فطار"},
	{key:"home.addons",group:"أقسام القائمة",label:"قسم الإضافات",sources:["المقبلات","إضافات"],defaultText:"إضافات"},
	{key:"home.drinks",group:"أقسام القائمة",label:"قسم المشروبات",sources:["المشروبات"],defaultText:"المشروبات"},
	{key:"home.add",group:"بطاقات المنتجات",label:"زر الإضافة",sources:["أضف","إضافة"],defaultText:"إضافة"},
	{key:"product.add",group:"صفحة المنتج",label:"زر إضافة المنتج",sources:["أضف للطلب"],defaultText:"إضافة إلى الطلب"},
	{key:"product.checkout",group:"صفحة المنتج",label:"زر إتمام الطلب",sources:["روح للطلب"],defaultText:"الانتقال إلى الطلب"},
	{key:"product.more",group:"صفحة المنتج",label:"العودة للقائمة",sources:["شوف المينيو"],defaultText:"عرض قائمة الطعام"},
	{key:"product.related",group:"صفحة المنتج",label:"عنوان المنتجات المشابهة",sources:["كمان من"],defaultText:"منتجات أخرى من"},
	{key:"cart.empty",group:"السلة",label:"السلة الفارغة",sources:["لا توجد منتجات في السلة"],defaultText:"لا توجد منتجات في السلة"},
	{key:"cart.menu",group:"السلة",label:"زر قائمة الطعام",sources:["عرض قائمة الطعام"],defaultText:"عرض قائمة الطعام"},
	{key:"checkout.title",group:"إتمام الطلب",label:"عنوان الصفحة وزر التأكيد",sources:["إتمام الطلب","تأكيد الطلب"],defaultText:"تأكيد الطلب"},
	{key:"checkout.intro",group:"إتمام الطلب",label:"عنوان بيانات التوصيل",sources:["بيانات طلب التوصيل"],defaultText:"بيانات طلب التوصيل"},
	{key:"checkout.introText",group:"إتمام الطلب",label:"شرح العنوان",sources:["أدخل المنطقة والعنوان التفصيلي، وستظهر رسوم التوصيل والإجمالي قبل التأكيد."],defaultText:"أدخل المنطقة والعنوان التفصيلي، وستظهر رسوم التوصيل والإجمالي قبل التأكيد."},
	{key:"checkout.customer",group:"إتمام الطلب",label:"اسم المستلم",sources:["اسم المستلم"],defaultText:"اسم المستلم"},
	{key:"checkout.phone",group:"إتمام الطلب",label:"رقم الهاتف",sources:["رقم الهاتف"],defaultText:"رقم الهاتف"},
	{key:"checkout.area",group:"إتمام الطلب",label:"المنطقة",sources:["المنطقة"],defaultText:"المنطقة"},
	{key:"checkout.street",group:"إتمام الطلب",label:"اسم الشارع",sources:["اسم الشارع"],defaultText:"اسم الشارع"},
	{key:"checkout.payment",group:"الدفع",label:"عنوان طريقة الدفع",sources:["طريقة الدفع"],defaultText:"طريقة الدفع"},
	{key:"checkout.cash",group:"الدفع",label:"الدفع النقدي",sources:["الدفع نقدًا عند الاستلام"],defaultText:"الدفع نقدًا عند الاستلام"},
	{key:"checkout.instapay",group:"الدفع",label:"الدفع عبر إنستاباي",sources:["الدفع عبر إنستاباي"],defaultText:"الدفع عبر إنستاباي"},
	{key:"confirmation.orderNumber",group:"تأكيد الطلب",label:"رقم الطلب",sources:["رقم الطلب"],defaultText:"رقم الطلب"},
	{key:"confirmation.paymentStatus",group:"تأكيد الطلب",label:"حالة الدفع",sources:["حالة الدفع"],defaultText:"حالة الدفع"},
	{key:"confirmation.tracking",group:"تأكيد الطلب",label:"متابعة الطلب",sources:["متابعة الطلب"],defaultText:"متابعة الطلب"},
	{key:"footer.delivery",group:"التذييل",label:"وصف التوصيل",sources:["توصيل لحد باب البيت","توصيل حتى باب المنزل"],defaultText:"توصيل حتى باب المنزل"},
	{key:"footer.rights",group:"التذييل",label:"حقوق النشر",sources:["كل الحقوق محفوظة","جميع الحقوق محفوظة"],defaultText:"جميع الحقوق محفوظة"},
]as const
export type SiteCopyKey=(typeof SITE_COPY_FIELDS)[number]["key"];export type SiteCopyValues=Record<string,string>
