import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
test('readiness polling, event identity, permission and kitchen-only readiness logic are unchanged',()=>{
 let s=readFileSync(new URL('../components/wasl/preparation-alerts.tsx',import.meta.url),'utf8');
 assert.equal(s.split("import { useEffect, useRef, useState, type ReactNode } from \"react\";\n").length,2);s=s.replace("import { useEffect, useRef, useState, type ReactNode } from \"react\";\n","import { useEffect, useRef, useState } from \"react\";\n");
 assert.equal(s.split("export default function PreparationAlerts({ accountId, render }: { accountId: string; render?:(content:ReactNode)=>ReactNode }) {\n").length,2);s=s.replace("export default function PreparationAlerts({ accountId, render }: { accountId: string; render?:(content:ReactNode)=>ReactNode }) {\n","export default function PreparationAlerts({ accountId }: { accountId: string }) {\n");
 assert.equal(s.split("  const content=!orders.length && !failed?null:<section aria-label=\"جاهزية طلبات المطعم\" className=\"bigcard\" style={{marginBottom:16}}>\n").length,2);s=s.replace("  const content=!orders.length && !failed?null:<section aria-label=\"جاهزية طلبات المطعم\" className=\"bigcard\" style={{marginBottom:16}}>\n","  if(!orders.length && !failed)return null;\n  return <section aria-label=\"جاهزية طلبات المطعم\" className=\"portal-review-notice\">\n");
 assert.equal(s.split("    {permission===\"default\" && <button className=\"btn btn-o\" type=\"button\" onClick={enable}>تفعيل تنبيهات الجاهزية</button>}\n    <p style={{fontSize:12}}>وقت التجهيز تقريبي؛ الجاهزية يؤكدها المطبخ. التنبيهات أثناء فتح التطبيق.</p>\n").length,2);s=s.replace("    {permission===\"default\" && <button className=\"btn btn-o\" type=\"button\" onClick={enable}>تفعيل تنبيهات الجاهزية</button>}\n    <p style={{fontSize:12}}>وقت التجهيز تقريبي؛ الجاهزية يؤكدها المطبخ. التنبيهات أثناء فتح التطبيق.</p>\n","    {permission===\"default\" && <button type=\"button\" onClick={enable}>تفعيل تنبيهات الجاهزية</button>}\n    <p>وقت التجهيز تقديري. التنبيه يعتمد على إعلان المطبخ جاهزية الطلب. تنبيهات هذه النسخة تحتاج التطبيق مفتوحًا واتصالًا؛ إشعارات الخلفية لم تُفعّل بعد.</p>\n");
 assert.equal(s.split("  </section>;\n  return render?render(content):content;\n").length,2);s=s.replace("  </section>;\n  return render?render(content):content;\n","  </section>;\n");
 assert.equal(createHash('sha1').update(`blob ${Buffer.byteLength(s)}\0`).update(s).digest('hex'),'a03f777449f096b45418c3959f17c2d058af4e83');
});
