"use server"

import { revalidatePath } from "next/cache"
import { and, eq } from "drizzle-orm"
import { branches, db, orders, orderStatusEnum, payments, staff } from "@el7bboB/db"
import { requireBranchAccess, type StaffSession } from "@/lib/staff-session"

type OrderStatus=(typeof orderStatusEnum.enumValues)[number]
function revalidateBranchScreens(branchCode:string){revalidatePath(`/staff/${branchCode}`);revalidatePath(`/staff/${branchCode}/cashier`);revalidatePath(`/staff/${branchCode}/delivery`);revalidatePath(`/staff/${branchCode}/kitchen`)}
function requireFrontOfHouseRole(session:StaffSession){if(session.role==="kitchen")throw new Error("هذا الإجراء متاح للكاشير أو مدير الفرع فقط.")}
async function loadAuthorizedOrder(orderId:string,branchCode:string){const session=await requireBranchAccess(branchCode);const[row]=await db.select({order:orders}).from(orders).innerJoin(branches,eq(orders.branchId,branches.id)).where(and(eq(orders.id,orderId),eq(branches.code,branchCode)));if(!row)throw new Error("الطلب غير موجود في هذا الفرع.");const[payment]=await db.select().from(payments).where(eq(payments.orderId,orderId)).limit(1);return{session,order:row.order,payment:payment??null}}
async function actorStaffId(session:StaffSession){const[row]=await db.select({id:staff.id}).from(staff).where(eq(staff.userId,session.userId)).limit(1);return row?.id??null}
const NEXT_STATUS:Partial<Record<OrderStatus,OrderStatus>>={queued:"in_progress",in_progress:"ready",ready:"completed"}
export async function advanceOrderStatus(orderId:string,branchCode:string){const{session,order}=await loadAuthorizedOrder(orderId,branchCode);if(order.status==="pending_payment")throw new Error("يجب تأكيد الدفع قبل إرسال الطلب للتجهيز.");const next=NEXT_STATUS[order.status];if(!next)return;if(session.role==="kitchen"&&next==="completed")throw new Error("تأكيد التسليم مسؤولية الكاشير أو مدير الفرع.");await db.update(orders).set({status:next,updatedAt:new Date()}).where(and(eq(orders.id,orderId),eq(orders.status,order.status)));revalidateBranchScreens(branchCode)}
export async function cancelOrder(orderId:string,branchCode:string){const{session,order}=await loadAuthorizedOrder(orderId,branchCode);requireFrontOfHouseRole(session);if(order.status==="completed")throw new Error("لا يمكن إلغاء طلب تم تسليمه.");await db.update(orders).set({status:"cancelled",updatedAt:new Date()}).where(eq(orders.id,orderId));revalidateBranchScreens(branchCode)}
export async function confirmPayment(orderId:string,branchCode:string){const{session,order,payment}=await loadAuthorizedOrder(orderId,branchCode);requireFrontOfHouseRole(session);if(!payment)throw new Error("لم يتم العثور على عملية الدفع.");if(payment.status==="confirmed")return;const staffId=await actorStaffId(session),now=new Date();await db.transaction(async(tx)=>{await tx.update(payments).set({status:"confirmed",confirmedAt:now,confirmedByStaffId:staffId}).where(eq(payments.id,payment.id));if(order.status==="pending_payment")await tx.update(orders).set({status:"queued",updatedAt:now}).where(and(eq(orders.id,orderId),eq(orders.status,"pending_payment")))});revalidateBranchScreens(branchCode)}
export async function completeDeliveryOrder(orderId:string,branchCode:string){const{session,order,payment}=await loadAuthorizedOrder(orderId,branchCode);requireFrontOfHouseRole(session);if(order.channel!=="online_delivery")throw new Error("هذا الإجراء مخصص لطلبات التوصيل.");if(order.status!=="ready"&&order.status!=="completed")throw new Error("يجب أن يكون الطلب جاهزًا قبل تأكيد التسليم.");if(!payment)throw new Error("لم يتم العثور على عملية الدفع.");if(payment.method==="instapay"&&payment.status!=="confirmed")throw new Error("يجب مراجعة تحويل إنستاباي وتأكيده قبل التسليم.");const staffId=await actorStaffId(session),now=new Date();await db.transaction(async(tx)=>{if(payment.status!=="confirmed")await tx.update(payments).set({status:"confirmed",confirmedAt:now,confirmedByStaffId:staffId}).where(eq(payments.id,payment.id));await tx.update(orders).set({status:"completed",updatedAt:now}).where(eq(orders.id,orderId))});revalidateBranchScreens(branchCode)}
