"use client"

import { useTransition } from "react"
import Link from "next/link"
import { Bike, Check, Clock, Loader2, MapPin, MessageSquare, Phone, Store, Wallet, X } from "lucide-react"
import type { StaffOrder } from "@/lib/orders/staff-orders"
import { advanceOrderStatus, cancelOrder, completeDeliveryOrder, confirmPayment } from "./actions"

const STATUS_LABELS: Record<string,string>={pending_payment:"مراجعة التحويل",queued:"في الطابور",in_progress:"بيتحضر",ready:"جاهز",completed:"اتسلم",cancelled:"اتلغى"}
const STATUS_TONE: Record<string,string>={pending_payment:"bg-[var(--terracotta)]/12 text-[var(--terracotta)]",queued:"bg-[var(--sesame)] text-[var(--ink)]/70",in_progress:"bg-[var(--amber)]/22 text-[var(--amber-deep)]",ready:"bg-[var(--zaatar)]/15 text-[var(--zaatar)]",completed:"bg-[var(--ink)]/8 text-[var(--ink)]/55",cancelled:"bg-[var(--ink)]/8 text-[var(--ink)]/40"}
const NEXT_ACTION_LABEL:Record<string,string>={pending_payment:"تأكيد الدفع",queued:"ابدأ التحضير",in_progress:"جاهز للتسليم",ready:"تم التسليم"}
// The stored display number is BRANCH-YYMMDD-NNNN; on screen the operator
// only needs the sequence big and bold — the branch/date prefix stays tiny.
function splitOrderNumber(d:string){const p=d.split("-"),last=p[p.length-1],n=Number(last);return p.length>1&&last!==""&&!Number.isNaN(n)?{prefix:p.slice(0,-1).join("-"),num:String(n)}:{prefix:"",num:d}}


export function OrderCard({branchCode,order,surface="operations"}:{branchCode:string;order:StaffOrder;surface?:"operations"|"delivery"}){
 const num=splitOrderNumber(order.displayNumber)
 const [isPending,startTransition]=useTransition(),isFinal=order.status==="completed"||order.status==="cancelled",isDelivery=order.channel==="online_delivery",paymentConfirmed=order.paymentStatus==="confirmed"
 const nextLabel=surface==="delivery"?(order.status==="pending_payment"?"تأكيد تحويل إنستاباي":order.status==="ready"?(paymentConfirmed?"تم التسليم":"تم التسليم والتحصيل"):null):NEXT_ACTION_LABEL[order.status]
 function handleAdvance(){startTransition(async()=>{if(surface==="delivery"&&order.status==="ready")await completeDeliveryOrder(order.id,branchCode);else if(order.status==="pending_payment")await confirmPayment(order.id,branchCode);else await advanceOrderStatus(order.id,branchCode)})}
 function handleCancel(){startTransition(async()=>{await cancelOrder(order.id,branchCode)})}
 return <div className="card flex flex-col gap-3 p-4">
  <div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2"><span className="flex flex-col leading-none">{num.prefix?<span dir="ltr" className="num text-[10px] font-bold tracking-wider text-[var(--ink)]/40">{num.prefix}-</span>:null}<span className="num text-4xl font-black text-[var(--amber-deep)]">{num.num}</span></span><span className="chip-outline text-[11px]">{isDelivery?<Bike className="h-3 w-3"/>:<Store className="h-3 w-3"/>}{isDelivery?"توصيل":"من المكان"}</span></div><span className={`shrink-0 rounded-full px-3 py-1 text-xs font-black ${STATUS_TONE[order.status]??"bg-slate-100"}`}>{STATUS_LABELS[order.status]??order.status}</span></div>
  <ul className="flex flex-col gap-2">{order.items.map((item,index)=><li key={index} className="flex flex-col gap-1"><span className="flex items-center gap-2 text-sm font-bold text-[var(--ink)]/80"><span className="num flex h-6 min-w-6 items-center justify-center rounded-lg bg-[var(--sesame)] px-1 text-xs font-black text-[var(--amber-deep)]">{item.quantity}</span>{item.nameAr}</span>{item.addons.length>0?<span className="ps-8 text-xs font-bold text-[var(--ink)]/50">+ {item.addons.join(" ، ")}</span>:null}{item.note?<span className="ms-8 flex items-start gap-1.5 rounded-xl border border-[var(--amber-deep)]/35 bg-[var(--sesame)] px-2.5 py-2 text-xs font-bold"><MessageSquare className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{item.note}</span>:null}</li>)}</ul>
  {order.customerNote?<div className="flex items-start gap-2 rounded-xl border border-[var(--terracotta)]/35 bg-[var(--terracotta)]/8 px-3 py-2.5"><MessageSquare className="mt-0.5 h-4 w-4 shrink-0 text-[var(--terracotta)]"/><div><p className="text-[11px] font-black text-[var(--terracotta)]">ملاحظات العميل</p><p className="mt-0.5 text-sm font-bold">{order.customerNote}</p></div></div>:null}
  {order.deliveryAddress?<div className="flex items-start gap-2 rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] px-3 py-2.5"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[var(--terracotta)]"/><div><p className="text-[11px] font-black text-[var(--ink)]/45">عنوان التوصيل</p><p className="mt-0.5 text-sm font-bold">{order.deliveryAddress}</p></div></div>:null}
  <div className="hairline"/><div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 text-xs font-bold text-[var(--ink)]/55"><span className="num font-black text-[var(--ink)]">{order.totalEGP} ج.م</span><span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5"/>{new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Africa/Cairo"}).format(new Date(order.createdAt))}</span>{order.paymentMethod?<span className="flex items-center gap-1.5"><Wallet className="h-3.5 w-3.5"/>{order.paymentMethod==="cash"?"كاش":"إنستاباي"}<span className={paymentConfirmed?"text-[var(--zaatar)]":"text-[var(--terracotta)]"}>{paymentConfirmed?"مدفوع":order.paymentMethod==="cash"&&isDelivery?"يتحصل عند التسليم":"محتاج تأكيد"}</span></span>:null}{order.customerName?<span>{order.customerName}</span>:null}{order.customerPhone?<a href={`tel:${order.customerPhone}`} dir="ltr" className="num flex items-center gap-1.5 font-black"><Phone className="h-3.5 w-3.5"/>{order.customerPhone}</a>:null}</div>
  {surface==="delivery"&&(order.status==="queued"||order.status==="in_progress")?<p className="rounded-xl bg-[var(--surface-muted)] px-3 py-2 text-center text-xs font-black text-[var(--ink)]/50">{order.status==="queued"?"مستني المطبخ يبدأ":"جاري التحضير في المطبخ"}</p>:null}
  <div className="mt-auto flex gap-2">{nextLabel?<button type="button" disabled={isPending} onClick={handleAdvance} className="btn btn-primary flex-1 rounded-xl px-3 py-2.5 text-sm">{isPending?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4" strokeWidth={3}/>} {nextLabel}</button>:null}{!isFinal?<button type="button" disabled={isPending} onClick={handleCancel} className="btn rounded-xl border border-[var(--terracotta)]/45 px-3 py-2.5 text-sm text-[var(--terracotta)]"><X className="h-4 w-4"/> إلغاء</button>:null}<Link href={`/staff/${branchCode}/orders/${order.id}/invoice`} target="_blank" className="btn rounded-xl border px-3 py-2.5 text-sm">فاتورة</Link></div>
 </div>
}
