"use client"

import { useMemo, useState, useTransition } from "react"
import { Check, Loader2, Search, SlidersHorizontal } from "lucide-react"
import { saveMixSettings } from "./actions"

type Row = { slug:string; nameAr:string; category:"base_item"|"addon"; menuPriceEGP:number; available:boolean; enabled:boolean; priceEGP:number; sortOrder:number }
export function MixSettingsPanel({ initialRows }:{ initialRows:Row[] }) {
	const [rows,setRows]=useState(initialRows), [query,setQuery]=useState(""), [pending,startTransition]=useTransition(), [message,setMessage]=useState<{ok:boolean;text:string}|null>(null)
	const shown=useMemo(() => rows.filter((row) => row.nameAr.includes(query.trim())),[rows,query]), enabledCount=rows.filter((row)=>row.enabled).length
	function patch(slug:string,updates:Partial<Row>){setRows((current)=>current.map((row)=>row.slug===slug?{...row,...updates}:row))}
	function save(){setMessage(null);startTransition(async()=>{try{await saveMixSettings(rows.map((row,index)=>({slug:row.slug,enabled:row.enabled&&row.available,priceEGP:row.priceEGP,sortOrder:index})));setMessage({ok:true,text:"تم حفظ أصناف الميكس وأسعار الإضافات."})}catch(error){setMessage({ok:false,text:error instanceof Error?error.message:"تعذر حفظ الإعدادات."})}})}
	return <div className="space-y-5"><section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] p-5"><div><h2 className="font-black">الأصناف المتاحة</h2><p className="mt-1 text-xs font-bold text-[var(--ink)]/45"><span className="num">{enabledCount}</span> صنف مفعّل داخل الميكس</p></div><label className="relative"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--ink)]/35" /><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="بحث عن صنف" className="input h-11 w-52 pe-3 ps-9 text-sm" /></label></div><div className="divide-y divide-[var(--line)]">{shown.map((row)=><div key={row.slug} className={`grid items-center gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_150px_110px] ${!row.available?"bg-[var(--surface-muted)] opacity-55":""}`}><label className="flex cursor-pointer items-center gap-3"><input type="checkbox" checked={row.enabled&&row.available} disabled={!row.available} onChange={(event)=>patch(row.slug,{enabled:event.target.checked})} className="h-5 w-5 accent-[var(--amber-deep)]" /><span><span className="block text-sm font-black">{row.nameAr}</span><span className="text-[11px] font-bold text-[var(--ink)]/40">سعره الأساسي: <span className="num">{row.menuPriceEGP}</span> ج.م {!row.available?"— غير متاح في المنيو":""}</span></span></label><label className="flex items-center gap-2"><span className="text-xs font-bold text-[var(--ink)]/50">سعر الإضافة</span><input type="number" min="0" max="1000" step="0.5" value={row.priceEGP} disabled={!row.enabled||!row.available} onChange={(event)=>patch(row.slug,{priceEGP:Number(event.target.value)})} className="input num h-11 w-20 text-center text-sm" /></label><span className={`rounded-full px-3 py-1.5 text-center text-xs font-black ${row.enabled&&row.available?"bg-[var(--zaatar)]/10 text-[var(--zaatar)]":"bg-[var(--ink)]/5 text-[var(--ink)]/40"}`}>{row.enabled&&row.available?"متاح في الميكس":"غير متاح"}</span></div>)}</div></section>{message?<p className={`rounded-2xl p-3 text-sm font-black ${message.ok?"bg-[var(--zaatar)]/10 text-[var(--zaatar)]":"bg-[var(--terracotta)]/10 text-[var(--terracotta)]"}`}>{message.text}</p>:null}<button type="button" onClick={save} disabled={pending} className="btn btn-primary w-full py-4 text-base">{pending?<Loader2 className="h-5 w-5 animate-spin"/>:<Check className="h-5 w-5"/>}{pending?"جارٍ حفظ الإعدادات...":"حفظ إعدادات الميكس"}</button><div className="flex items-start gap-3 rounded-2xl border border-[var(--line)] bg-white p-4 text-xs font-bold leading-relaxed text-[var(--ink)]/55"><SlidersHorizontal className="mt-0.5 h-4 w-4 shrink-0 text-[var(--amber-deep)]" />أي تعديل هنا ينعكس على الموقع فورًا، والسعر المستخدم في الطلب يُراجع من الخادم لمنع التلاعب.</div></div>
}
