"use server"
import {and,asc,desc,eq,inArray,ne} from 'drizzle-orm'
import {auditLog,branches,db,orders,payments,siteSettings,staff} from '@el7bboB/db'
import {requireOwner} from '../actions'
import {loadStaffOrders,type StaffOrder} from '@/lib/orders/staff-orders'
import {INSTAPAY_LINK} from '@/lib/instapay-provided'
import {confirmPayment} from '../../[branchCode]/actions'
import {revalidatePath} from 'next/cache'
export type OperatingOrder=StaffOrder&{branchCode:string;branchName:string;reference:string|null}
export type CashWithDriver={id:string;branchCode:string;displayNumber:string;customerName:string|null;customerPhone:string|null;totalEGP:number;createdAt:string}
export type InstapayInfo={address:string|null;walletNumber:string|null;accountName:string|null;paymentLink:string|null}
export type Board={orders:OperatingOrder[];cashWithDriver:CashWithDriver[];instapay:InstapayInfo|null;branches:{code:string;name:string;active:boolean}[];loadedAt:string}
export async function loadOperatingBoard():Promise<Board>{await requireOwner();const sites=await db.select().from(branches).orderBy(asc(branches.name));const batches=await Promise.all(sites.map(async b=>(await loadStaffOrders({branchId:b.id,statuses:['pending_payment','queued','in_progress','ready']})).map(o=>({...o,branchCode:b.code,branchName:b.name,reference:null as string|null}))));const all=batches.flat().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),ids=all.map(o=>o.id);if(ids.length){const refs=await db.select({orderId:payments.orderId,reference:payments.instapayReference}).from(payments).where(inArray(payments.orderId,ids));const byId=new Map(refs.map(p=>[p.orderId,p.reference]));for(const o of all)o.reference=byId.get(o.id)??null}// Cash-on-delivery orders already out with a driver stay listed (with their
// total) until the owner confirms collecting the money — otherwise that cash
// is invisible the moment the order leaves the open board.
const cashRows=await db.select({id:orders.id,displayNumber:orders.displayNumber,customerName:orders.customerName,customerPhone:orders.customerPhone,totalEGP:orders.totalEGP,createdAt:orders.createdAt,branchCode:branches.code}).from(orders).innerJoin(branches,eq(orders.branchId,branches.id)).innerJoin(payments,eq(payments.orderId,orders.id)).where(and(eq(orders.status,'completed'),eq(orders.channel,'online_delivery'),eq(payments.method,'cash'),ne(payments.status,'confirmed'))).orderBy(desc(orders.createdAt)).limit(50)
const[settings]=await db.select().from(siteSettings).where(eq(siteSettings.id,'default'))
return {orders:all,cashWithDriver:cashRows.map(r=>({id:r.id,branchCode:r.branchCode,displayNumber:r.displayNumber,customerName:r.customerName,customerPhone:r.customerPhone,totalEGP:Number(r.totalEGP),createdAt:r.createdAt.toISOString()})),instapay:settings?{address:settings.instapayAddress??null,walletNumber:settings.instapayWalletNumber??null,accountName:settings.instapayAccountName??null,paymentLink:INSTAPAY_LINK}:null,branches:sites.map(b=>({code:b.code,name:b.name,active:b.isActive})),loadedAt:new Date().toISOString()}}
export async function operateOrder(id:string,branchCode:string,operation:'start'|'ready'|'complete'|'payment'|'collect',expectedStatus:string):Promise<{ok:boolean;message:string}>{await requireOwner();try{if(!/^[0-9a-f-]{36}$/i.test(id)||branchCode.length>80)throw new Error('راجع الطلب');const[row]=await db.select({order:orders}).from(orders).innerJoin(branches,eq(orders.branchId,branches.id)).where(and(eq(orders.id,id),eq(branches.code,branchCode)));if(!row)throw new Error('راجع الطلب');if(row.order.status!==expectedStatus)throw new Error('حالة الطلب تغيرت. راجع أحدث حالة قبل التنفيذ');const[payment]=await db.select().from(payments).where(eq(payments.orderId,id)).limit(1);if(!payment)throw new Error('لم يتم العثور على وسيلة الدفع');if(['failed','refunded'].includes(payment.status))throw new Error('الدفع يحتاج مراجعة قبل تنفيذ الطلب');if(operation==='collect'){if(row.order.status!=='completed'||row.order.channel!=='online_delivery'||payment.method!=='cash')throw new Error('التحصيل ينطبق على طلبات الدليفري النقدية المسلّمة فقط');if(payment.status!=='confirmed')await confirmPayment(id,branchCode);revalidatePath('/staff/owner/orders');revalidatePath(`/staff/${branchCode}/delivery`);return {ok:true,message:'تم تسجيل استلام النقدية من الدليفري ✅'}}if(['cancelled','completed'].includes(row.order.status))throw new Error('الطلب لم يعد مفتوحًا؛ حدّث الشاشة');
if(operation==='payment'){if(payment.status!=='confirmed')await confirmPayment(id,branchCode)}
else{if(payment.method==='instapay'&&payment.status!=='confirmed')throw new Error('أكد وصول تحويل إنستاباي أولًا');if(operation==='complete'){if(row.order.status!=='ready')throw new Error('الطلب يجب أن يكون جاهزًا أولًا');// Delivery completion and cash collection happen together: the driver hands
// the order and takes the payment in the same moment, so the order closes
// fully with no separate cash-tracking step.
if(row.order.channel==='online_delivery'){if(payment.method==='cash'&&payment.status!=='confirmed')await confirmPayment(id,branchCode)}else{if(payment.status!=='confirmed')throw new Error('أكد تحصيل النقدية أولًا')}await db.update(orders).set({status:'completed',updatedAt:new Date()}).where(and(eq(orders.id,id),eq(orders.status,'ready')))}else{const next=operation==='start'&&row.order.status==='queued'?'in_progress':operation==='ready'&&row.order.status==='in_progress'?'ready':null;if(!next)throw new Error('انتقال حالة غير مسموح');await db.update(orders).set({status:next,updatedAt:new Date()}).where(and(eq(orders.id,id),eq(orders.status,row.order.status)))}}
revalidatePath('/staff/owner/orders');revalidatePath(`/staff/${branchCode}/kitchen`);revalidatePath(`/staff/${branchCode}/delivery`);revalidatePath(`/staff/${branchCode}/cashier`);return {ok:true,message:'تم تحديث الطلب'}
}catch(error){console.error('[owner-operations]',error);return {ok:false,message:error instanceof Error&&!/sql|query|postgres|connect|relation/i.test(error.message)?error.message:'تعذر تأكيد العملية. حدّث الشاشة قبل إعادة المحاولة'}}}

const OPEN_STATUSES=['pending_payment','queued','in_progress','ready'] as const
export async function cancelAllOpenOrders():Promise<{ok:boolean;message:string}>{const owner=await requireOwner();try{const cancelled=await db.update(orders).set({status:'cancelled',updatedAt:new Date()}).where(inArray(orders.status,[...OPEN_STATUSES])).returning({id:orders.id});const[actor]=await db.select({id:staff.id}).from(staff).where(eq(staff.userId,owner.userId)).limit(1);await db.insert(auditLog).values({actorStaffId:actor?.id??null,action:'cancel_all_open_orders',entityType:'order',entityId:'*',reason:'إلغاء جماعي للطلبات المفتوحة بطلب المالك (تنظيف تجارب)',metadataJson:{count:cancelled.length}});const sites=await db.select({code:branches.code}).from(branches);revalidatePath('/staff/owner/orders');for(const site of sites){revalidatePath(`/staff/${site.code}`);revalidatePath(`/staff/${site.code}/kitchen`);revalidatePath(`/staff/${site.code}/delivery`);revalidatePath(`/staff/${site.code}/cashier`)}return{ok:true,message:cancelled.length?`تم إلغاء ${cancelled.length} طلب مفتوح. الطلبات محفوظة بحالة «ملغي» ولم تُحذف.`:'لا توجد طلبات مفتوحة حاليًا'}}catch(error){console.error('[owner-cancel-all]',error);return{ok:false,message:'تعذر إلغاء الطلبات المفتوحة. حدّث الصفحة وأعد المحاولة'}}}
