"use client"
import { useState, type ReactNode, type FormEvent } from "react"
import Link from "next/link"
import { saveOwnerCommand, loadPosDay, type OwnerData, type OwnerCommand } from "./actions"
const money=(n:number)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(n)
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const tabs=['ملخصي','قفل اليوم','المصروفات','الخامات والمشتريات','التحضير والهالك','الوصفات والإنتاج','السجل والتصدير']
function Field({label,children}:{label:string;children:ReactNode}){return <label className="ow-field"><span>{label}</span>{children}</label>}
function NumberInput({name,defaultValue=0,required=true}:{name:string;defaultValue?:number;required?:boolean}){return <input type="number" name={name} min="0" max="100000000" step="0.0001" required={required} defaultValue={defaultValue}/>}
export function OwnerPanel({initial,name}:{initial:OwnerData;name:string}){
 const [snapshot,setSnapshot]=useState(initial),[tab,setTab]=useState(0),[date,setDate]=useState(today()),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[mode,setMode]=useState<'manual'|'pos'>('manual'),[pos,setPos]=useState<{cash:number;instapay:number}|null>(null)
 const data=snapshot.data,day=data.days.find(d=>d.date===date),items=data.entries.filter(e=>e.date===date),cash=day?.cash??0,transfer=day?.instapay??0,drawer=items.reduce((s,e)=>s+e.drawer,0),expected=(day?.opening??0)+cash-drawer,difference=day?day.counted-expected:0
 const operating=items.filter(e=>e.kind==='expense'&&!['مسحوبات شخصية','أصول وتجهيزات','سلف عاملين'].includes(e.category??'')).reduce((s,e)=>s+e.amount,0),purchases=items.filter(e=>e.kind==='purchase').reduce((s,e)=>s+e.amount,0),waste=items.filter(e=>e.kind==='waste').reduce((s,e)=>s+e.amount,0)
 async function submit(command:Omit<OwnerCommand,'token'|'date'>,form:HTMLFormElement){
  if(pending)return;setPending(true);setMessage('')
  const token=form.dataset.token||crypto.randomUUID();form.dataset.token=token
  try{const result=await saveOwnerCommand({...command,date,token},snapshot.revision);if(result.snapshot)setSnapshot(result.snapshot);setMessage(result.message);if(result.ok){delete form.dataset.token;if(command.type!=='day')form.reset()}else if(result.snapshot)delete form.dataset.token}catch{setMessage('تعذر الاتصال. بيانات النموذج محفوظة هنا؛ اضغط حفظ مجددًا.')}finally{setPending(false)}
 }
 function handle(type:OwnerCommand['type'],event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,v=new FormData(f),str=(key:string)=>String(v.get(key)??''),num=(key:string)=>Number(v.get(key)??0)
  const command:Omit<OwnerCommand,'date'|'token'>={type,name:str('name'),unit:str('unit'),quantity:num('quantity'),cost:num('cost'),materialId:str('materialId'),outputId:str('outputId'),outputQuantity:num('outputQuantity'),amount:num('amount'),note:str('note'),category:str('category'),drawer:v.get('drawer')==='on',stockKind:str('stockKind') as OwnerCommand['stockKind'],mode,opening:num('opening'),cash:num('cash'),instapay:num('instapay'),counted:num('counted'),price:num('price')}
  if(type==='recipe')command.lines=data.materials.map(m=>({materialId:m.id,quantity:num('q-'+m.id)})).filter(l=>l.quantity>0)
  void submit(command,f)
 }
 const materialSelect=(field='materialId')=><select required name={field} defaultValue=""><option value="" disabled>اختار الخامة</option>{data.materials.map(m=><option key={m.id} value={m.id}>{m.name} — {m.unit}</option>)}</select>
 const button=<button disabled={pending} className="ow-button">{pending?'جارٍ الحفظ…':'حفظ في حسابي'}</button>
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),revision:snapshot.revision,...data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='el7bbob-owner-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function exportCsv(){const rows=[['التاريخ','النوع','الوصف','التصنيف','المبلغ','المسحوب من الدرج','الكمية','ملاحظات'],...data.entries.map(e=>[e.date,e.kind,e.label,e.category??'',e.amount,e.drawer,e.quantity??'',e.note])];const escape=(v:unknown)=>'"'+String(v).replace(/^[=+@\-]/,"'").replace(/"/g,'""')+'"';const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='el7bbob-owner-ledger.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main dir="rtl" className="ow-root"><style>{`
 .ow-root{min-height:100vh;background:#f6f3ed;color:#1e2723;padding:24px;font-family:inherit}.ow-wrap{max-width:1220px;margin:auto}.ow-header{background:#182720;color:white;padding:28px;border-radius:24px;display:flex;justify-content:space-between;gap:20px;align-items:center}.ow-header h1{font-size:28px;font-weight:900;margin:8px 0}.ow-header p{color:#cad3cd}.ow-badge{color:#f4b542;font-size:13px;font-weight:800}.ow-header a{color:#f4b542}.ow-date{display:flex;align-items:center;gap:12px;margin:20px 0;flex-wrap:wrap}.ow-date input{padding:10px;border:1px solid #ddd;border-radius:12px;background:white}.ow-tabs{display:flex;gap:8px;overflow:auto;padding:0 0 14px}.ow-tabs button{white-space:nowrap;padding:12px 17px;border-radius:12px;background:white;border:1px solid #ddd;font-weight:800}.ow-tabs button.active{background:#182720;color:#f4b542;border-color:#182720}.ow-card{background:white;border:1px solid #e5e2da;border-radius:20px;padding:22px;margin-bottom:18px}.ow-card h2{font-size:21px;font-weight:900;margin-bottom:12px}.ow-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ow-stat{background:white;padding:20px;border-radius:18px;border:1px solid #e5e2da}.ow-stat strong{display:block;font-size:27px;margin:10px 0}.ow-stat small,.ow-help{color:#647269;line-height:1.8;font-size:13px}.ow-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.ow-field{display:flex;flex-direction:column;gap:7px;font-size:14px;font-weight:700}.ow-field input,.ow-field select,.ow-field textarea{width:100%;padding:12px;background:#fafaf7;border:1px solid #dedfd7;border-radius:12px;color:#1e2723}.ow-button{background:#f4b542;color:#182720;border-radius:12px;padding:13px 20px;font-weight:900;border:0}.ow-button:disabled{opacity:.5}.ow-wide{grid-column:1/-1}.ow-message{padding:14px;background:#fff2d0;border:1px solid #efcd80;border-radius:12px;margin:14px 0}.ow-table{width:100%;border-collapse:collapse;white-space:nowrap;font-size:14px}.ow-table th,.ow-table td{text-align:right;padding:13px;border-bottom:1px solid #eee}.ow-scroll{overflow:auto}.ow-chip{display:inline-block;background:#f2ead6;color:#7a5819;border-radius:8px;padding:5px 9px;font-size:12px}.ow-list{display:flex;gap:12px;flex-wrap:wrap}.ow-empty{padding:28px;text-align:center;color:#647269}.ow-footer{font-size:12px;color:#647269;padding:20px 0;line-height:1.9}.ow-recipe{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.ow-card ul{padding-right:22px;list-style:disc;line-height:2}@media(max-width:760px){.ow-root{padding:12px}.ow-header{padding:20px;align-items:flex-start;flex-direction:column}.ow-header h1{font-size:23px}.ow-grid,.ow-recipe{grid-template-columns:repeat(2,minmax(0,1fr))}.ow-form{grid-template-columns:1fr}.ow-stat strong{font-size:22px}.ow-card{padding:17px}}`}</style>
 <div className="ow-wrap"><header className="ow-header"><div><span className="ow-badge">الحَبّوب / مساحة المالك الخاصة</span><h1>أهلًا {name}، شغلك كله تحت عينك</h1><p>تشغيل المالك الآن • النظام الحالي والكاشير يفضلوا زي ما هم</p></div><Link href="/staff/admin">العودة للإدارة ←</Link></header>
 <div className="ow-date"><label>يوم التشغيل: <input type="date" value={date} onChange={e=>{setDate(e.target.value);setPos(null);setMode(data.days.find(d=>d.date===e.target.value)?.mode??'manual')}}/></label><span className="ow-chip">خاص بالمالك • محفوظ على السيرفر</span></div>
 <nav className="ow-tabs" aria-label="أقسام المالك">{tabs.map((t,i)=><button key={t} onClick={()=>{setTab(i);setMessage('');if(i===1)setMode(day?.mode??'manual')}} className={tab===i?'active':''}>{t}</button>)}</nav>
 {message&&<p role="status" className="ow-message">{message}</p>}
 {tab===0&&<><div className="ow-grid">{[{t:'مبيعات اليوم المسجلة',v:cash+transfer,s:day?'مصدر واحد: '+(day.mode==='manual'?'تقفيل يدوي':'الكاشير — لقطة وقت التقفيل'):'لم يتم تقفيل اليوم بعد'},{t:'مصروفات تشغيل مدفوعة',v:operating,s:'لا تشمل الأصول والمسحوبات والسلف'},{t:'مشتريات خامات',v:purchases,s:'مخزون، وليست كلها تكلفة مبيعات'},{t:'قيمة المخزون الحالية',v:data.materials.reduce((s,m)=>s+m.stock*m.cost,0),s:'بمتوسط التكلفة المرجح المسجل'}].map(x=><div className="ow-stat" key={x.t}><span>{x.t}</span><strong>{money(x.v)} ج.م</strong><small>{x.s}</small></div>)}</div><section className="ow-card" style={{marginTop:18}}><h2>تقفيل اليوم في دقيقة</h2><div className="ow-list"><span>نقدية متوقعة: <b>{money(expected)}</b></span><span>نقدية فعلية: <b>{day?money(day.counted):'لم تُسجل'}</b></span><span>فرق الدرج: <b>{day?money(difference):'—'}</b></span><span>هالك بتكلفة مسجلة: <b>{money(waste)}</b></span></div><p className="ow-help">المتوقع = عهدة بداية اليوم + المبيعات النقدية − المصروفات والمشتريات المدفوعة من الدرج. InstaPay لا يدخل في الدرج.</p><button className="ow-button" onClick={()=>{setMode(day?.mode??'manual');setTab(1)}}>قفل يومي</button></section><section className="ow-card"><h2>أول مرة؟ ابدأ بالترتيب ده</h2><ul><li>عرّف الخامات ووحداتها ورصيدها الافتتاحي.</li><li>سجل المشتريات والمصروفات، وحدد لو خرجت من درج المبيعات.</li><li>سجل التحضير والهالك أو جرد الكميات الفعلية.</li><li>عرّف حصص الوصفات عشان تعرف التكلفة والعدد المتاح نظريًا.</li><li>آخر اليوم سجل المبيعات الإجمالية والنقدية الفعلية فقط.</li></ul><p className="ow-help">لا توجد بيانات تجريبية أو أرباح وهمية. ربح اليوم الدقيق يحتاج تكلفة استهلاك موثوقة ومبيعات أصناف؛ هذه النسخة تعرض الإيراد والمصروفات والمخزون ولا تسمي الفرق «صافي ربح».</p></section></>}
 {tab===1&&<section className="ow-card"><h2>قفل اليوم — من غير تسجيل كل طلب</h2><form key={date+':'+(day?.savedAt??'new')} className="ow-form" onSubmit={e=>handle('day',e)}><Field label="مصدر مبيعات اليوم"><select value={mode} disabled={!!day} onChange={e=>{setMode(e.target.value as 'manual'|'pos');setPos(null)}}><option value="manual">إجمالي يدوي — التشغيل الحالي</option><option value="pos">المبيعات المؤكدة من النظام الحالي</option></select></Field><Field label="عهدة النقدية أول اليوم"><NumberInput name="opening" defaultValue={day?.opening}/></Field>{mode==='manual'?<><Field label="إجمالي مبيعات نقدي"><NumberInput name="cash" defaultValue={day?.cash}/></Field><Field label="إجمالي مبيعات InstaPay"><NumberInput name="instapay" defaultValue={day?.instapay}/></Field></>:<div className="ow-wide"><button type="button" className="ow-button" disabled={pending} onClick={async()=>{setPending(true);try{setPos(await loadPosDay(date))}catch{setMessage('تعذر قراءة المبيعات')}finally{setPending(false)}}}>عرض المبيعات المؤكدة</button><p>نقدي: {money(pos?.cash??day?.cash??0)} • InstaPay: {money(pos?.instapay??day?.instapay??0)}</p><p className="ow-help">يُعاد حسابها على السيرفر عند الحفظ. لا تُجمع مع إجمالي يدوي.</p></div>}<Field label="النقدية الموجودة فعلًا آخر اليوم"><NumberInput name="counted" defaultValue={day?.counted}/></Field><Field label="ملاحظات اليوم"><textarea name="note" maxLength={500} defaultValue={day?.note}/></Field><p className="ow-help ow-wide">الحفظ مرة ثانية يعدّل نفس اليوم، ولا يكرر المبيعات. مصدر اليوم ثابت بعد أول حفظ لمنع الخلط.</p>{button}</form></section>}
 {tab===2&&<section className="ow-card"><h2>سجل مصروف — إيجار، أجور، وكل احتياجات المحل</h2><form className="ow-form" onSubmit={e=>handle('expense',e)}><Field label="الوصف"><input name="name" required maxLength={120} placeholder="مثال: أجرة مساعد / فاتورة غاز"/></Field><Field label="التصنيف"><select name="category">{['تشغيل','إيجار','أجور','سلف عاملين','مرافق','صيانة','تسويق','أصول وتجهيزات','مسحوبات شخصية'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="المبلغ المدفوع بالجنيه"><NumberInput name="amount"/></Field><Field label="ملاحظات / اسم العامل / رقم الفاتورة"><input name="note" maxLength={500}/></Field><label className="ow-wide"><input type="checkbox" name="drawer"/> دفعت من درج مبيعات هذا اليوم</label>{button}</form><p className="ow-help">هذا سجل مبالغ مدفوعة؛ الالتزامات غير المسددة والرواتب الدورية ليست محسوبة تلقائيًا. السلف والأصول والمسحوبات مفصولة عن مصروفات التشغيل.</p></section>}
 {tab===3&&<><section className="ow-card"><h2>الخامات ورصيدها الحالي</h2><p className="ow-help">الكيلو واللتر والقطعة هي وحدات التسجيل. 100 جرام = 0.1 كيلو؛ 100 مل = 0.1 لتر. لا تغيّر وحدة خامة بعد تسجيلها.</p><div className="ow-scroll"><table className="ow-table"><thead><tr><th>الخامة</th><th>الرصيد</th><th>الوحدة</th><th>متوسط تكلفة الوحدة</th><th>قيمة المخزون</th></tr></thead><tbody>{data.materials.map(m=><tr key={m.id}><td>{m.name}</td><td>{money(m.stock)}</td><td>{m.unit}</td><td>{money(m.cost)}</td><td>{money(m.stock*m.cost)}</td></tr>)}</tbody></table></div>{!data.materials.length&&<p className="ow-empty">أضف أول خامة تحت، مثل فول خام أو فول مجهز أو عيش.</p>}</section><section className="ow-card"><h2>تعريف خامة ورصيد افتتاحي</h2><form className="ow-form" onSubmit={e=>handle('material',e)}><Field label="اسم الخامة"><input name="name" required maxLength={120}/></Field><Field label="وحدة التسجيل"><select name="unit"><option>كيلو</option><option>لتر</option><option>قطعة</option></select></Field><Field label="الرصيد الافتتاحي"><NumberInput name="quantity"/></Field><Field label="تكلفة الوحدة بالجنيه"><NumberInput name="cost"/></Field>{button}</form></section><section className="ow-card"><h2>شراء خامات</h2><form className="ow-form" onSubmit={e=>handle('purchase',e)}><Field label="الخامة">{materialSelect()}</Field><Field label="الكمية بوحدة الخامة"><NumberInput name="quantity"/></Field><Field label="إجمالي قيمة الشراء والتكاليف المباشرة"><NumberInput name="amount"/></Field><Field label="المورد / الفاتورة / ملاحظات"><input name="note" maxLength={500}/></Field><label className="ow-wide"><input type="checkbox" name="drawer"/> دفعت من درج مبيعات هذا اليوم</label>{button}</form><p className="ow-help">شراء مدفوع بالكامل في هذه النسخة. لا تسجل شراءً آجلًا هنا باعتباره مدفوعًا. متوسط التكلفة يتحدث وفق قيمة الرصيد الموجود والكمية الجديدة.</p></section></>}
 {tab===4&&<><section className="ow-card"><h2>دفعة تحضير — من خام إلى جاهز</h2><p className="ow-help">مثال: فول خام بالكيلو ← فول مجهز بالكيلو. أنشئ الاثنين كخامتين مختلفتين. تكلفة الخام المستخدم تنتقل للناتج؛ الإضافات الأخرى تُسجل في الوصفة أو كاستخدام منفصل. هذا تحويل مكوّن واحد، وليس دفعة متعددة الخامات.</p><form className="ow-form" onSubmit={e=>handle('production',e)}><Field label="الخامة المستخدمة">{materialSelect()}</Field><Field label="الكمية المستخدمة بوحدتها"><NumberInput name="quantity"/></Field><Field label="الخامة الناتجة">{materialSelect('outputId')}</Field><Field label="الكمية الناتجة فعلًا بوحدتها"><NumberInput name="outputQuantity"/></Field><Field label="ملاحظات"><input name="note" maxLength={500}/></Field>{button}</form></section><section className="ow-card"><h2>استخدام، هالك، أو جرد فعلي</h2><form className="ow-form" onSubmit={e=>handle('stock',e)}><Field label="نوع الحركة"><select name="stockKind"><option value="waste">هالك — يخصم الكمية</option><option value="usage">استخدام / أكل عاملين / ضيافة</option><option value="count">جرد — ضبط الرصيد على الموجود فعلًا</option></select></Field><Field label="الخامة">{materialSelect()}</Field><Field label="الكمية بوحدة الخامة"><NumberInput name="quantity"/></Field><Field label="السبب / ملاحظات"><input name="note" maxLength={500}/></Field><p className="ow-help ow-wide">في الجرد: اكتب إجمالي الموجود، وليس الفرق. في الهالك والاستخدام: اكتب الكمية المراد خصمها. كل حركة محفوظة في السجل، والجرد لا يدعي أن الفرق كله مبيعات.</p>{button}</form></section></>}
 {tab===5&&<><section className="ow-card"><h2>الوصفات: تكلفة الحصة والعدد المتاح نظريًا</h2><div className="ow-recipe">{data.recipes.map(r=>{const cost=r.lines.reduce((s,l)=>s+l.quantity*(data.materials.find(m=>m.id===l.materialId)?.cost??0),0),available=Math.min(...r.lines.map(l=>Math.floor((data.materials.find(m=>m.id===l.materialId)?.stock??0)/l.quantity)));return <div className="ow-card" key={r.id}><h3><b>{r.name}</b></h3><p>تكلفة الحصة: {money(cost)} ج.م</p><p>سعر البيع: {money(r.price)} ج.م</p><p>هامش مكونات فقط: {money(r.price-cost)} ج.م</p><strong>المتاح نظريًا: {available} وحدة</strong><p className="ow-help">لا يشمل التشغيل والهالك. الأصناف تشترك في الخامات؛ لا تجمع أعدادها كأنها مخزون مستقل.</p></div>})}</div>{!data.recipes.length&&<p className="ow-empty">عرّف وصفات الأصناف التي ستفتح بها أولًا.</p>}</section><section className="ow-card"><h2>إضافة أو تعديل وصفة</h2><form className="ow-form" onSubmit={e=>handle('recipe',e)}><Field label="اسم المنتج — نفس الاسم يعدّل وصفته"><input name="name" required maxLength={120}/></Field><Field label="سعر بيع الوحدة"><NumberInput name="price"/></Field><p className="ow-help ow-wide">اكتب حصة وحدة واحدة بوحدة كل خامة. مثال: 80 جرام فول مجهز = 0.08 كيلو، ورغيف واحد = 1 قطعة. اترك غير المستخدم صفرًا. أدخل التغليف كخامة لو عايز تضيف تكلفته.</p>{data.materials.map(m=><Field key={m.id} label={m.name+' — '+m.unit}><NumberInput name={'q-'+m.id}/></Field>)}{button}</form></section></>}
 {tab===6&&<section className="ow-card"><h2>السجل والنسخة الاحتياطية</h2><div className="ow-list"><button onClick={exportData} className="ow-button">تحميل كل بياناتي JSON</button><button onClick={exportCsv} className="ow-button">تحميل سجل Excel / CSV</button></div><p className="ow-help">السجل لا يحذف العمليات. يعرض آخر 150 حركة؛ التصدير يشمل جميع الحركات. التاريخ تاريخ تشغيل؛ رصيد المخزون يعبر عن الحالة الحالية بعد جميع الحركات وليس جردًا تاريخيًا.</p><div className="ow-scroll"><table className="ow-table"><thead><tr><th>التاريخ</th><th>العملية</th><th>المبلغ / التكلفة</th><th>من الدرج</th><th>الكمية</th><th>ملاحظات</th></tr></thead><tbody>{[...data.entries].reverse().slice(0,150).map(e=><tr key={e.id}><td>{e.date}</td><td>{e.label}{e.category&&' — '+e.category}</td><td>{money(e.amount)}</td><td>{money(e.drawer)}</td><td>{e.quantity===undefined?'—':money(e.quantity)}</td><td>{e.note}</td></tr>)}</tbody></table></div></section>}
 <footer className="ow-footer">مساحة المالك مستقلة عن واجهة العملاء. لا تخصم طلبات الموقع الخامات هنا تلقائيًا حاليًا؛ المخزون يتغير بالمشتريات والتحضير والاستخدام والهالك والجرد المسجل. مصدر الكاشير يقرأ المقبوضات المؤكدة فقط، ويُحفظ بدل الإجمالي اليدوي وليس فوقه. لا تغييرات على المنيو أو الأسعار أو شاشات الموظفين الحالية.</footer></div></main>
}
