"use server"

import { loadSandwichBreadCatalog } from "../../sandwich-bread-store"
import { expandBreadProducts, resolveBreadSale, isSandwichBread } from "../../sandwich-bread"
import { and,desc,eq,gte,inArray,ne } from "drizzle-orm"
import { z } from "zod"
import { acceptsProductExtra, extrasEligible, isProductExtra } from "../../product-extras"
import { loadProductExtrasConfigs } from "../../product-extras-store"
import { loadMealSelections } from "../../meal-settings-store"
import { MAX_MEAL_UNITS, mealKindForSlug, priceMeal } from "../../meal-config"
import { allocateOrderNumber,db,deliveryZones,ensureDeliveryZones,menuItems,orderItems,orders,payments } from "@el7bboB/db"
import { computeLineTotal } from "@el7bboB/core"
import { deductBranchStockForOrder } from "@/lib/orders/inventory"
import { CUSTOM_MIX_SLUG,MIX_MAX_COMPONENTS,MIX_MIN_COMPONENTS,parseMixSettings } from "../../mix/mix-config"
import { loadDeliveryBranch } from "../delivery-branch"
import { dispatchWaslDelivery } from "@/lib/wasl-dispatch"

const NOTE_MAX_LENGTH=200,PHONE_PATTERN=/^01[0125][0-9]{8}$/
const schema=z.object({branchCode:z.string().min(1),channel:z.enum(["in_store","cart_kiosk","online_pickup","online_delivery"]),paymentMethod:z.enum(["cash","instapay"]),deliveryZoneId:z.string().uuid("يرجى تحديد منطقة التوصيل"),instapayReference:z.string().trim().max(60).optional(),customerName:z.string().trim().min(2,"يرجى إدخال اسم المستلم").max(80),customerPhone:z.string().trim().regex(PHONE_PATTERN,"يرجى إدخال رقم هاتف مصري صحيح"),deliveryAddress:z.string().trim().min(10,"يرجى إدخال عنوان توصيل تفصيلي").max(300),customerNote:z.string().trim().max(NOTE_MAX_LENGTH).optional(),customerLat:z.number().min(-90).max(90).optional(),customerLng:z.number().min(-180).max(180).optional(),lines:z.array(z.object({menuItemId:z.string().uuid(),quantity:z.number().int().min(1).max(20),addonMenuItemIds:z.array(z.string().uuid()).max(MAX_MEAL_UNITS).default([]),note:z.string().trim().max(NOTE_MAX_LENGTH).optional()})).min(1,"لا توجد منتجات في السلة").max(60)}).superRefine((value,ctx)=>{if(value.paymentMethod==="instapay"&&(!value.instapayReference||value.instapayReference.length<4))ctx.addIssue({code:z.ZodIssueCode.custom,path:["instapayReference"],message:"يرجى إدخال رقم مرجع التحويل"})})
export type DeliveryCheckoutInput=z.infer<typeof schema>;export type CreateOrderResult={ok:true;orderId:string;displayNumber:string;totalEGP:number}|{ok:false;message:string}
export async function createOrder(input:DeliveryCheckoutInput):Promise<CreateOrderResult>{
	const parsed=schema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"يرجى مراجعة بيانات الطلب"}
	try{return await createOrderFromParsed(parsed.data)}catch(error){console.error("[create-order]",error);return{ok:false,message:error instanceof Error&&!/sql|query|postgres|connect|relation|constraint|duplicate/i.test(error.message)?error.message:"تعذر إتمام الطلب حاليًا. راجع السلة ثم حاول مرة أخرى."}}
}
async function createOrderFromParsed(parsed:DeliveryCheckoutInput):Promise<CreateOrderResult>{
	const branch=await loadDeliveryBranch();if(!branch||branch.code!==parsed.branchCode)throw new Error("خدمة التوصيل غير متاحة حاليًا.")
	await ensureDeliveryZones();const[zone]=await db.select().from(deliveryZones).where(and(eq(deliveryZones.id,parsed.deliveryZoneId),eq(deliveryZones.isActive,true))).limit(1);if(!zone)throw new Error("منطقة التوصيل غير متاحة. يرجى اختيار منطقة أخرى.")
	const allIds=Array.from(new Set(parsed.lines.flatMap((line)=>[line.menuItemId,...line.addonMenuItemIds]))),products=await db.select().from(menuItems).where(inArray(menuItems.id,allIds)),byId=new Map(products.map((item)=>[item.id,item]));let subtotalEGP=0
	const mealSelections=parsed.lines.some((line)=>!!mealKindForSlug(byId.get(line.menuItemId)?.slug??""))?await loadMealSelections():{tray:null,box:null}
	const breadCatalog=await loadSandwichBreadCatalog(),sales=new Map(parsed.lines.map(line=>[line.menuItemId,resolveBreadSale(line.menuItemId,breadCatalog.products,breadCatalog.configs)]));const extraConfigs=await loadProductExtrasConfigs(parsed.lines.map(line=>sales.get(line.menuItemId)!.parent.id))
	const rows=parsed.lines.map((line)=>{const sale=sales.get(line.menuItemId)!,product={...byId.get(line.menuItemId),...sale.product};if(!product?.isAvailable||isProductExtra(product.slug))throw new Error("أحد المنتجات غير متاح حاليًا. يرجى تحديث الصفحة ومراجعة السلة.");const mealKind=mealKindForSlug(product.slug),isCustomMix=product.slug===CUSTOM_MIX_SLUG,unitPriceEGP=mealKind?0:Number(product.priceEGP),selectedIds=Array.from(new Set(line.addonMenuItemIds));if(!Number.isFinite(unitPriceEGP)||unitPriceEGP<0||(!isCustomMix&&!mealKind&&unitPriceEGP<=0))throw new Error(`سعر ${product.nameAr} غير متاح حاليًا.`);if(!mealKind&&line.addonMenuItemIds.length>10)throw new Error("عدد الإضافات غير صالح.");if(isCustomMix&&(selectedIds.length<MIX_MIN_COMPONENTS||selectedIds.length>MIX_MAX_COMPONENTS))throw new Error(`يجب اختيار من ${MIX_MIN_COMPONENTS} إلى ${MIX_MAX_COMPONENTS} مكونات للميكس.`);const mixSettings=new Map(parseMixSettings(product.photosJson).filter((item)=>item.enabled).map((item)=>[item.slug,item] as const));const addons=mealKind?priceMeal(mealKind,line.addonMenuItemIds,expandBreadProducts(breadCatalog.products.filter(item=>item.isAvailable&&!isProductExtra(item.slug)&&!isSandwichBread(item.slug)).map(item=>({...item,priceEGP:Number(item.priceEGP)})),breadCatalog.products,breadCatalog.configs),mealSelections[mealKind]):selectedIds.map((id)=>{const addon=byId.get(id);if(!addon||isSandwichBread(addon.slug)||(!addon.isAvailable&&!isProductExtra(addon.slug)))throw new Error("إحدى المكونات غير متاحة حاليًا.");if(isProductExtra(addon.slug)&&(!extrasEligible(sale.parent.slug,sale.parent.category)||!acceptsProductExtra(extraConfigs[sale.parent.id]??null,addon)))throw new Error("إحدى الإضافات لم تعد متاحة لهذا المنتج. راجع السلة.");if(isCustomMix){const setting=mixSettings.get(addon.slug);if(!setting)throw new Error("إحدى مكونات الميكس غير متاحة.");return{menuItemId:addon.id,nameAr:addon.nameAr,priceEGP:setting.priceEGP}}if(!acceptsProductExtra(extraConfigs[sale.parent.id]??null,addon))throw new Error("إحدى الإضافات لم تعد متاحة لهذا المنتج. راجع السلة.");if(addon.category!=="addon")throw new Error("إحدى الإضافات غير متاحة حاليًا.");const addonPrice=Number(addon.priceEGP);if(!Number.isFinite(addonPrice)||addonPrice<0)throw new Error("سعر إحدى الإضافات غير صالح.");return{menuItemId:addon.id,nameAr:addon.nameAr,priceEGP:addonPrice}});const lineTotalEGP=computeLineTotal({unitPriceEGP,quantity:line.quantity,addonsEGP:addons.map((addon)=>addon.priceEGP)});subtotalEGP+=lineTotalEGP;return{menuItemId:product.id,quantity:line.quantity,unitPriceEGP:String(unitPriceEGP),addonsJson:addons,note:line.note||null,lineTotalEGP:String(lineTotalEGP)}})
	const deliveryFeeEGP=Number(zone.feeEGP);if(!Number.isFinite(deliveryFeeEGP)||deliveryFeeEGP<0)throw new Error("تعذر احتساب رسوم التوصيل.");const totalEGP=subtotalEGP+deliveryFeeEGP,fullAddress=`${zone.name} — ${parsed.deliveryAddress}`
	const[recent]=await db.select({id:orders.id,displayNumber:orders.displayNumber,totalEGP:orders.totalEGP}).from(orders).where(and(eq(orders.branchId,branch.id),eq(orders.customerPhone,parsed.customerPhone),eq(orders.deliveryAddress,fullAddress),eq(orders.totalEGP,String(totalEGP)),ne(orders.status,"cancelled"),gte(orders.createdAt,new Date(Date.now()-30_000)))).orderBy(desc(orders.createdAt)).limit(1);if(recent)return{ok:true,orderId:recent.id,displayNumber:recent.displayNumber,totalEGP:Number(recent.totalEGP)}
	const instapayReference=parsed.paymentMethod==="instapay"?parsed.instapayReference?.trim().toUpperCase():undefined;if(instapayReference){const[used]=await db.select({id:payments.id}).from(payments).where(eq(payments.instapayReference,instapayReference)).limit(1);if(used)throw new Error("رقم مرجع التحويل مستخدم في طلب سابق. يرجى مراجعة الرقم.")}
	const displayNumber=await allocateOrderNumber(branch.id,branch.code),order=await db.transaction(async(tx)=>{const[created]=await tx.insert(orders).values({branchId:branch.id,displayNumber,channel:"online_delivery",status:parsed.paymentMethod==="cash"?"queued":"pending_payment",subtotalEGP:String(subtotalEGP),deliveryFeeEGP:String(deliveryFeeEGP),totalEGP:String(totalEGP),customerName:parsed.customerName,customerPhone:parsed.customerPhone,deliveryAddress:fullAddress,customerNote:parsed.customerNote||null,customerLat:parsed.customerLat===undefined?null:String(parsed.customerLat),customerLng:parsed.customerLng===undefined?null:String(parsed.customerLng)}).returning();if(!created)throw new Error("تعذر إنشاء الطلب.");await tx.insert(orderItems).values(rows.map((row)=>({...row,orderId:created.id})));await tx.insert(payments).values({orderId:created.id,method:parsed.paymentMethod,status:parsed.paymentMethod==="cash"?"pending":"awaiting_confirmation",amountEGP:String(totalEGP),instapayReference});return created})
	dispatchWaslDelivery({merchant:"مطعم الحبوب",merchantZone:"المنصورة",fromAddr:"ميدان مشعل — المنصورة، الدقهلية",destZone:zone.name,toAddr:fullAddress,fee:deliveryFeeEGP,total:totalEGP,pay:parsed.paymentMethod==="cash"?"كاش":"إنستاباي",kind:"أوردر طعام",readyMinutes:15,customerPhone:parsed.customerPhone,customerName:parsed.customerName,note:parsed.customerNote,source:"el7bbob"})
	try{await deductBranchStockForOrder(branch.id,parsed.lines.map(line=>({...line,menuItemId:sales.get(line.menuItemId)!.parent.id,addonMenuItemIds:line.addonMenuItemIds.map(id=>isSandwichBread(byId.get(id)?.slug??"")?resolveBreadSale(id,breadCatalog.products,breadCatalog.configs).parent.id:id)})))}catch(error){console.error(`Inventory deduction failed for order ${order.id}`,error)}return{ok:true,orderId:order.id,displayNumber,totalEGP}
}
