"use client"

import { useEffect, useMemo, useState } from "react"
import { AnimatePresence, motion } from "motion/react"
import { Bike, CheckCircle2, MapPin, Search } from "lucide-react"

export type DeliveryZoneOption = { id: string; name: string; feeEGP: number }
type Props = { zones: DeliveryZoneOption[]; value: string; onChange: (zoneId: string, typedArea: string) => void; error?: string }
function normalize(value: string) { return value.trim().toLowerCase().replace(/[أإآ]/g, "ا").replace(/ة/g, "ه").replace(/ى/g, "ي") }
export function DeliveryAreaCombobox({ zones, value, onChange, error }: Props) {
	const selected = zones.find((zone) => zone.id === value) ?? null
	const [query, setQuery] = useState(selected?.name ?? "")
	const [focused, setFocused] = useState(false)
	const matches = useMemo(() => { const needle = normalize(query); if (needle.length < 2) return []; return zones.filter((zone) => normalize(zone.name).includes(needle)).slice(0, 6) }, [query, zones])
	useEffect(() => { const onlyMatch = matches[0]; if (selected || normalize(query).length < 3 || matches.length !== 1 || !onlyMatch) return; onChange(onlyMatch.id, query) }, [matches, onChange, query, selected])
	function typeArea(next: string) { setQuery(next); if (!selected || normalize(next) !== normalize(selected.name)) onChange("", next) }
	return <div className="relative"><label className="mb-2 flex items-center justify-between text-sm font-black"><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[var(--amber-deep)]" /> المنطقة</span><span className="text-[11px] font-bold text-[var(--ink)]/40">اكتب اسم المنطقة</span></label><div className={`relative rounded-2xl border bg-white transition ${error ? "border-[var(--terracotta)]" : selected ? "border-[var(--zaatar)]/50 shadow-[0_0_0_3px_rgba(79,122,85,.08)]" : focused ? "border-[var(--amber-deep)] shadow-[var(--ring)]" : "border-[var(--line)]"}`}><Search className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--ink)]/35" /><input value={query} onFocus={() => setFocused(true)} onBlur={() => window.setTimeout(() => setFocused(false),160)} onChange={(event) => typeArea(event.target.value)} placeholder="اسم المنطقة أو الشارع" autoComplete="off" className="h-14 w-full rounded-2xl bg-transparent pe-12 ps-12 text-sm font-black outline-none" />{selected ? <CheckCircle2 className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[var(--zaatar)]" /> : null}</div><AnimatePresence>{focused && !selected && matches.length > 1 ? <motion.div initial={{ opacity:0,y:-6,scale:.98 }} animate={{ opacity:1,y:0,scale:1 }} exit={{ opacity:0,y:-4,scale:.98 }} className="absolute inset-x-0 top-[82px] z-40 overflow-hidden rounded-2xl border border-[var(--line)] bg-white p-1.5 shadow-[var(--shadow-lg)]">{matches.map((zone) => <button key={zone.id} type="button" onMouseDown={() => { setQuery(zone.name); onChange(zone.id,zone.name); setFocused(false) }} className="flex w-full items-center justify-between rounded-xl px-3 py-3 text-right transition hover:bg-[var(--sesame)]"><span className="font-black">{zone.name}</span><span className="num rounded-full bg-[var(--amber)]/15 px-2.5 py-1 text-xs font-black text-[var(--amber-deep)]">{zone.feeEGP} ج.م</span></button>)}</motion.div> : null}</AnimatePresence>{selected ? <motion.div initial={{ opacity:0,y:4 }} animate={{ opacity:1,y:0 }} className="mt-2 flex items-center justify-between rounded-2xl bg-[var(--zaatar)]/10 px-3.5 py-2.5 text-xs font-black text-[var(--zaatar)]"><span className="flex items-center gap-2"><Bike className="h-4 w-4" /> رسوم التوصيل إلى {selected.name}</span><span className="num text-sm">{selected.feeEGP} ج.م</span></motion.div> : null}{!selected && normalize(query).length >= 3 && matches.length === 0 ? <p className="mt-2 rounded-xl bg-[var(--terracotta)]/8 px-3 py-2 text-xs font-bold text-[var(--terracotta)]">هذه المنطقة خارج نطاق التوصيل الحالي. يرجى إدخال اسم منطقة قريبة مدعومة.</p> : null}{error ? <p className="mt-1.5 text-xs font-bold text-[var(--terracotta)]">{error}</p> : null}</div>
}
