"use client"
import {useState,type FormEvent} from 'react'
import {useRouter,useSearchParams} from 'next/navigation'
import {Mail,Lock,Eye,EyeOff,Loader2} from 'lucide-react'
import {authClient} from '@/lib/auth-client'
export function LoginForm(){
 const router=useRouter(),searchParams=useSearchParams(),requested=searchParams.get('next')??'/staff'
 let next='/staff';try{const parsed=new URL(requested,'https://internal.invalid');if(parsed.origin==='https://internal.invalid'&&(parsed.pathname==='/staff'||parsed.pathname.startsWith('/staff/')))next=parsed.pathname+parsed.search}catch{/* Use the staff landing page for invalid redirects. */}
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[error,setError]=useState<string|null>(null),[isSubmitting,setIsSubmitting]=useState(false)
 async function handleSubmit(event:FormEvent){event.preventDefault();if(isSubmitting)return;setError(null);setIsSubmitting(true);try{const{error:signInError}=await authClient.signIn.email({email:email.trim().toLowerCase(),password});if(signInError){const code=String(signInError.code??''),status=Number(signInError.status??0);if(code==='INVALID_ORIGIN'||code==='INVALID_CALLBACK_URL'||code==='INVALID_REDIRECT_URL'||status===403)setError('عنوان الموقع غير مسموح لتسجيل الدخول. حدّث الصفحة بعد اكتمال تحديث الموقع، أو استخدم رابط Railway مؤقتًا.');else if(code==='INVALID_EMAIL_OR_PASSWORD'||status===401)setError('الإيميل أو كلمة السر غير صحيحة. راجع البيانات بدون مسافات إضافية.');else if(status===429)setError('محاولات دخول كثيرة. انتظر قليلًا ثم جرّب مرة أخرى.');else setError('تعذر تسجيل الدخول حاليًا. قد تكون المشكلة في الاتصال أو إعدادات الموقع، وليس كلمة السر.');return}router.push(next);router.refresh()}catch{setError('تعذر الاتصال بخدمة تسجيل الدخول. تحقق من الإنترنت وحدّث الصفحة ثم حاول مجددًا.')}finally{setIsSubmitting(false)}}
 return <form onSubmit={handleSubmit} className="flex w-full max-w-sm flex-col gap-4"><div className="flex flex-col gap-1.5"><label htmlFor="email" className="text-sm font-semibold">الإيميل</label><div className="relative"><Mail className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--ink)]/35"/><input id="email" type="email" required autoComplete="email" dir="ltr" value={email} onChange={event=>setEmail(event.target.value)} className="w-full rounded-xl border border-[var(--ink)]/15 py-2.5 pe-3 ps-9 outline-none transition focus:border-[var(--amber)]"/></div></div><div className="flex flex-col gap-1.5"><label htmlFor="password" className="text-sm font-semibold">كلمة السر</label><div className="relative"><Lock className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--ink)]/35"/><input id="password" type={showPassword?'text':'password'} required autoComplete="current-password" dir="ltr" value={password} onChange={event=>setPassword(event.target.value)} className="w-full rounded-xl border border-[var(--ink)]/15 py-2.5 pe-3 ps-9 outline-none transition focus:border-[var(--amber)]"/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'إخفاء كلمة السر':'إظهار كلمة السر'} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--ink)]/35 transition hover:text-[var(--ink)]/70">{showPassword?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></div>{error&&<p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-500">{error}</p>}<button type="submit" disabled={isSubmitting} className="flex items-center justify-center gap-2 rounded-xl bg-[var(--amber)] px-4 py-2.5 font-bold text-[var(--ink)] transition active:scale-[0.98] disabled:opacity-50">{isSubmitting&&<Loader2 className="h-4 w-4 animate-spin"/>}{isSubmitting?'جاري الدخول...':'دخول'}</button></form>
}
